case-build:
  stage: build
  tags:
    - build
  script:
    - bash build.bash case

case-test:
  stage: test
  tags:
    - build
  script: bash test.bash case
  coverage: /All\sfiles.*?\s+(\d+.\d+)/

case-deploy-dev:
  stage: deploy
  environment:
    name: dev
  tags:
    - trading
  script:
    - docker pull $DOCKER_REGISTRY/$DOCKER_PREFFIX/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA
    - docker tag $DOCKER_REGISTRY/$DOCKER_PREFFIX/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA $DOCKER_REGISTRY/$DOCKER_PREFFIX/$CI_PROJECT_NAME:latest
    - docker push $DOCKER_REGISTRY/$DOCKER_PREFFIX/$CI_PROJECT_NAME:latest
    - cd $DEPLOY_PATH_DEV
    - docker-compose up -d case-dev
