before_script:
  - docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

case-build:
  stage: build
  tags:
    - build
  script:
    - docker build -t case .

case-test:
  stage: test
  tags:
    - build
  script: bash test.bash
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
